server=http://localhost:4111/
apiVersion=api/v1/

uiRemote=http://localhost:4444/wd/hub
baseUiUrl=http://host.docker.internal:3000
browserSize=1920x1080
browser=chrome

# Database configuration
db.url=jdbc:postgresql://localhost:5433/nbank
db.username=postgres
db.password=postgres
db.driver=org.postgresql.Driver

