# Format: RequestClass=ResponseClass:field1=field1Response,field2=field2Response

CustomerResponse=CustomerDao:username=username,role=role,name=name
TransactionDto=TransactionDao:amount=amount
Accounts=AccountDao:accountNumber=accountNumber,id=id,balance=balance
