### Positive test. A user can deposit 5000 to self balance
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 1,
  "balance": 5000
}

### Negative test. A user cannot deposit 5001 to self balance
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 1,
  "balance": 5001
}

### Negative test. A user cannot deposit 0 to self balance
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 1,
  "balance": 0
}

### Positive test. A user can transfer 10000 to another user's account
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 10000
}

### Negative test. A user cannot transfer 0 to another user
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 0
}

### Negative test. A user cannot transfer 10001 to another user
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 10001
}

### Negative test. A user cannot transfer 10001 to another user
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 10001
}

### Negative test. A user has's enouth amount to transfer.
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 10000
}

### Negative test. A user has's enouth amount to transfer.
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 10000
}

### Positive test. A user can transfer to another account of theirs.
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "senderAccountId": 1,
  "receiverAccountId": 3,
  "amount": 500
}

### Positive test. A user can change a name.
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "name": "New Name"
}

### Negative test. A user cannot change a name that contains digits.
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "name": "Ne1w 3Name"
}

### Negative test. A user cannot change a name consisting of a single word.
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "name": "Name"
}

### Negative test. A user cannot change a name consisting of two words with no space between them.
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "name": "NewName"
}

