services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nbank
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d nbank" ]
      interval: 3s
      timeout: 3s
      retries: 15
    networks:
      - nbank-network

  backend:
    image: nobugsme/nbank:preprod_version_with_mocks
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/nbank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "4111:4111"
    networks:
      - nbank-network

  frontend:
    image: nobugsme/nbank-ui:preprod_version
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - nbank-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - nbank-network

  selenoid:
    image: aerokube/selenoid:latest-release
    environment:
      DOCKER_API_VERSION: "1.53"
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/:/etc/selenoid/:ro
    networks:
      - nbank-network
    command: [ "-container-network", "nbank-network" ]

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    ports:
      - "6567:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
    depends_on:
      - selenoid
    networks:
      - nbank-network

networks:
  nbank-network:
    name: nbank-network
